### PR TITLE
Changed Menu Bar to show File Menu in linux based systems

### PR DESCRIPTION
**Pull request by LiorBitton**
Solved #435.

### CODE REVIEW

**Comment by minorsecond** [comment]
Can one of the admins verify this patch?

**Comment by minorsecond** [comment]
Can one of the admins verify this patch?

**Comment by minorsecond** [comment]
@LiorBitton Thanks! Can you please create a branch from develop and cherry pick your changes into that and create a PR onto develop?

**Comment by minorsecond** [comment]
Actually I think you just accidentally created a PR to merge develop into master.

**Comment by LiorBitton** [comment]
Didn't mean to do that😅, I'll fix it soon.

**Pull request closed without merging**
