### PR TITLE
Update stats_updaters.cpp

### PR DESCRIPTION
**Pull request by Nikhil-1503**
## Description

Updated stats_updaters.cpp file to remove -nan when no drinks are entered.

## Motivation and Context

Closes issue #434 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by minorsecond** [comment]
Can one of the admins verify this patch?

**Comment by minorsecond** [comment]
Can one of the admins verify this patch?

**Comment by minorsecond** [comment]
This PR looks good, but can you please create a branch from `develop` and create a PR merging your changes into `develop`?

**Comment by Nikhil-1503** [comment]
So should I create a new branch 'develop' on my fork, or should I create a new fork which contains develop branch?

**Comment by minorsecond** [comment]
I think you should be able to just create a branch off of develop on your fork and then create a PR to merge it back into my develop.

**Comment by minorsecond** [comment]
Note: I just merged in changes on a bunch of files to develop so you'll have to pull changes first. I don't think they will interfere with your changes though.

**Pull request closed without merging**
